# # Backend/Tools/university/import_to_unitime.py

# import os
# import sys
# import requests
# from pydantic import BaseModel, Field
# from typing import Optional, Any
# from typing import Type

# # --- Project Path Setup ---
# PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "../../.."))
# if PROJECT_ROOT not in sys.path:
#     sys.path.append(PROJECT_ROOT)

# from Backend.tool_framework.base_tool import BaseTool

# # --- Pydantic Input Schema ---
# class ImportToUnitimeInput(BaseModel):
#     unitime_xml_data: str = Field(..., description="The complete XML data string to be imported into the Unitime system.")

# # --- Tool Class Definition ---
# class ImportToUnitimeTool(BaseTool):
#     """
#     A tool that takes XML data and sends it to the Unitime dataexchange API endpoint for processing.
#     """
#     name: str = "Import_Data_to_Unitime"
#     description: str = "Use this tool to import the final XML data generated by the AI model into the Unitime system."
#     # args_schema = ImportToUnitimeInput
#     args_schema: Type[BaseModel] = ImportToUnitimeInput
    
#     def _execute(self, unitime_xml_data: str) -> str:
#         print("\n" + "="*60)
#         print("--- VERIFICATION MODE: XML Received ---")
#         print("The agent is about to send the following XML to UniTime:")
#         print("\n")
#         print(unitime_xml_data) 
#         print("\n" + "="*60 + "\n")
        
#         return "SUCCESS: XML was generated and verified in VERIFICATION MODE. It was NOT sent to the real UniTime server."
#         # --- END VERIFICATION BLOCK ---

#         api_url = self.get_tool_config("UNITIME_API_URL")
#         api_key = self.get_tool_config("UNITIME_API_KEY")

#         if not api_url or not api_key:
#             return "Error: Unitime API URL or API Key is not configured in the environment."

#         headers = {
#             "Authorization": f"Bearer {api_key}",
#             "Content-Type": "application/xml"
#         }
#         try:
#             response = requests.post(api_url, data=unitime_xml_data.encode('utf-8'), headers=headers)
#             response.raise_for_status()  # This will raise an HTTPError for bad responses (4xx or 5xx)
#             return f"Successfully imported data to Unitime. Server response: {response.text}"
#         except requests.exceptions.HTTPError as http_err:
#             return f"Error: HTTP error occurred during Unitime import: {http_err} - Response: {http_err.response.text}"
#         except requests.exceptions.RequestException as req_err:
#             return f"Error: A critical request error occurred during Unitime import: {req_err}"


















import os
import sys
import requests
from requests.auth import HTTPBasicAuth 
from pydantic import BaseModel, Field
from typing import Optional, Any
from typing import Type

# --- Project Path Setup ---
PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "../../.."))
if PROJECT_ROOT not in sys.path:
    sys.path.append(PROJECT_ROOT)

from Backend.tool_framework.base_tool import BaseTool

# --- Pydantic Input Schema (UPDATED) ---
class ImportToUnitimeInput(BaseModel):
    # The tool now expects the filename to read from
    filename: str = Field(..., description="The name of the local XML batch file to import (e.g., 'unitime_batch.xml' for inserts or 'unitime_update.xml' for updates).")

# --- Tool Class Definition (UPDATED) ---
class ImportToUnitimeTool(BaseTool):
    """
    A tool that reads XML data from a specified local file and sends it to the 
    UniTime dataexchange API endpoint for processing.
    """
    # Renamed to match the agent's workflow (Import_Batch_File_to_Unitime)
    name: str = "Import_Batch_File_to_Unitime" 
    description: str = "Imports the content of a specified local XML file (e.g., unitime_batch.xml or unitime_update.xml) into the UniTime system via the API."
    args_schema: Type[BaseModel] = ImportToUnitimeInput
    
    # Updated signature to accept filename
    def _execute(self, filename: str) -> str:
        
        # --- Step 1: Read XML Data from Local File ---
        file_path = os.path.join(PROJECT_ROOT, filename)
        
        if not os.path.exists(file_path):
            return f"Error: The batch file '{filename}' was not found at path {file_path}. Cannot proceed with import."
            
        try:
            with open(file_path, "r", encoding="utf-8") as f:
                unitime_xml_data = f.read()
        except Exception as e:
            return f"Error: Failed to read content from file '{filename}': {e}"
        
        # --- Step 2: Load Credentials ---
        api_url = self.get_tool_config("UNITIME_API_URL")
        username = self.get_tool_config("UNITIME_USERNAME") 
        password = self.get_tool_config("UNITIME_PASSWORD") 
        
        if not api_url or not username or not password:
            return "Error: Missing UNITIME_API_URL, UNITIME_USERNAME, or UNITIME_PASSWORD in the environment configuration."

        headers = {
            "Content-Type": "application/xml;charset=UTF-8"
        }
        
        # --- Step 3: API Request ---
        try:
            print(f"--- ATTEMPTING TO POST XML from '{filename}' TO {api_url} using Basic Auth ---")
            
            response = requests.post(
                api_url, 
                data=unitime_xml_data.encode('utf-8'), # Use the content read from the file
                headers=headers,
                auth=HTTPBasicAuth(username, password)
            )
            
            response.raise_for_status() 
            
            if "text/html" in response.headers.get("Content-Type", ""):
                 return f"Successfully imported data from {filename} to UniTime. Server returned an HTML success page (Status: {response.status_code}). Server response: {response.text}"
            
            return f"Successfully imported data from {filename} to UniTime. Server response: {response.text}"
        
        except requests.exceptions.HTTPError as http_err:
            return f"Error: HTTP error occurred during UniTime import of {filename}: {http_err} - Response: {http_err.response.text}"
        except requests.exceptions.RequestException as req_err:
            return f"Error: A critical request error occurred during import of {filename}: {req_err}"